
modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="firmaciv"
version="0.2.1-alpha"
displayName="Firma: Civilization"
logoFile="icon.png"
authors="alekiponi"
credits = "Contributors: alekiponi, Traister101, EERussianGuy"
description='''
Firma: Civilization is an addon/expansion for TerraFirmaCraft focusing on key, civilization-building technologies missing from the base mod.

'''
[[dependencies.firmaciv]]
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[47.1.3,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.firmaciv]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.20.1,1.21.0)"
    ordering="NONE"
    side="BOTH"


[[dependencies.firmaciv]]
    modId="tfc"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

