TFC_WOODS: dict[str, str] = {"acacia": "Acacia",
                             "ash": "Ash",
                             "aspen": "Aspen",
                             "birch": "Birch",
                             "blackwood": "Blackwood",
                             "chestnut": "Chestnut",
                             "douglas_fir": "Douglas Fir",
                             "hickory": "Hickory",
                             "kapok": "Kapok",
                             "mangrove": "Mangrove",
                             "maple": "Maple",
                             "oak": "Oak",
                             "palm": "Palm",
                             "pine": "Pine",
                             "rosewood": "Rosewood",
                             "sequoia": "Sequoia",
                             "spruce": "Spruce",
                             "sycamore": "Sycamore",
                             "white_cedar": "White Cedar",
                             "willow": "Willow"}

DEFAULT_LANG = {

    "item.firmaciv.testitem": "They're waiting for you, Mr. Freeman. With the Test Item.",

    "entity.firmaciv.dugout_canoe.acacia": "Acacia Dugout Canoe",
    "entity.firmaciv.dugout_canoe.ash": "Ash Dugout Canoe",
    "entity.firmaciv.dugout_canoe.aspen": "Aspen Dugout Canoe",
    "entity.firmaciv.dugout_canoe.birch": "Birch Dugout Canoe",
    "entity.firmaciv.dugout_canoe.blackwood": "Blackwood Dugout Canoe",
    "entity.firmaciv.dugout_canoe.chestnut": "Chestnut Dugout Canoe",
    "entity.firmaciv.dugout_canoe.douglas_fir": "Douglas Fir Dugout Canoe",
    "entity.firmaciv.dugout_canoe.hickory": "Hickory Dugout Canoe",
    "entity.firmaciv.dugout_canoe.kapok": "Kapok Dugout Canoe",
    "entity.firmaciv.dugout_canoe.maple": "Maple Dugout Canoe",
    "entity.firmaciv.dugout_canoe.oak": "Oak Dugout Canoe",
    "entity.firmaciv.dugout_canoe.palm": "Palm Dugout Canoe",
    "entity.firmaciv.dugout_canoe.pine": "Pine Dugout Canoe",
    "entity.firmaciv.dugout_canoe.rosewood": "Rosewood Dugout Canoe",
    "entity.firmaciv.dugout_canoe.sequoia": "Sequoia Dugout Canoe",
    "entity.firmaciv.dugout_canoe.spruce": "Spruce Dugout Canoe",
    "entity.firmaciv.dugout_canoe.sycamore": "Sycamore Dugout Canoe",
    "entity.firmaciv.dugout_canoe.white_cedar": "White Cedar Dugout Canoe",
    "entity.firmaciv.dugout_canoe.willow": "Willow Dugout Canoe",

    "entity.firmaciv.rowboat.acacia": "Acacia Rowboat",
    "entity.firmaciv.rowboat.ash": "Ash Rowboat",
    "entity.firmaciv.rowboat.aspen": "Aspen Rowboat",
    "entity.firmaciv.rowboat.birch": "Birch Rowboat",
    "entity.firmaciv.rowboat.blackwood": "Blackwood Rowboat",
    "entity.firmaciv.rowboat.chestnut": "Chestnut Rowboat",
    "entity.firmaciv.rowboat.douglas_fir": "Douglas Fir Rowboat",
    "entity.firmaciv.rowboat.hickory": "Hickory Rowboat",
    "entity.firmaciv.rowboat.kapok": "KapokRowboat",
    "entity.firmaciv.rowboat.maple": "Maple Rowboat",
    "entity.firmaciv.rowboat.oak": "Oak Rowboat",
    "entity.firmaciv.rowboat.palm": "Palm Rowboat",
    "entity.firmaciv.rowboat.pine": "Pine Rowboat",
    "entity.firmaciv.rowboat.rosewood": "Rosewood Rowboat",
    "entity.firmaciv.rowboat.sequoia": "Sequoia Rowboat",
    "entity.firmaciv.rowboat.spruce": "Spruce Rowboat",
    "entity.firmaciv.rowboat.sycamore": "Sycamore Rowboat",
    "entity.firmaciv.rowboat.white_cedar": "White Cedar Rowboat",
    "entity.firmaciv.rowboat.willow": "Willow Rowboat",

    "entity.firmaciv.sloop.acacia": "Acacia Sloop",
    "entity.firmaciv.sloop.ash": "Ash Sloop",
    "entity.firmaciv.sloop.aspen": "Aspen Sloop",
    "entity.firmaciv.sloop.birch": "Birch Sloop",
    "entity.firmaciv.sloop.blackwood": "Blackwood Sloop",
    "entity.firmaciv.sloop.chestnut": "Chestnut Sloop",
    "entity.firmaciv.sloop.douglas_fir": "Douglas Fir Sloop",
    "entity.firmaciv.sloop.hickory": "Hickory Sloop",
    "entity.firmaciv.sloop.kapok": "KapokRowboat",
    "entity.firmaciv.sloop.maple": "Maple Sloop",
    "entity.firmaciv.sloop.oak": "Oak Sloop",
    "entity.firmaciv.sloop.palm": "Palm Sloop",
    "entity.firmaciv.sloop.pine": "Pine Sloop",
    "entity.firmaciv.sloop.rosewood": "Rosewood Sloop",
    "entity.firmaciv.sloop.sequoia": "Sequoia Sloop",
    "entity.firmaciv.sloop.spruce": "Spruce Sloop",
    "entity.firmaciv.sloop.sycamore": "Sycamore Sloop",
    "entity.firmaciv.sloop.white_cedar": "White Cedar Sloop",
    "entity.firmaciv.sloop.willow": "Willow Sloop",

    "entity.firmaciv.kayak": "Kayak",

    "entity.firmaciv.vehicle_part": "Vehicle Part",
    "entity.firmaciv.vehicle_cleat": "Cleat",

    "entity.firmaciv.compartment_chest": "Chest Compartment",
    "entity.firmaciv.compartment_workbench": "Workbench Compartment",
    "entity.firmaciv.compartment_log_pile": "Log Pile Compartment",
    "entity.firmaciv.compartment_large_vessel": "Large Vessel Compartment",
    "entity.firmaciv.compartment_empty": "Empty Compartment",

    "block.firmaciv.boat_frame": "Shipwright's Scaffolding",

    "block.firmaciv.thatch_roofing": "Thatch Roofing",

    "item.firmaciv.canoe_icon_only": "ICON ONLY",
    "item.firmaciv.canoe_with_paddle_icon_only": "ICON ONLY",
    "item.firmaciv.kayak_with_paddle_icon_only": "ICON ONLY",
    "item.firmaciv.rowboat_icon_only": "ICON ONLY",

    "itemGroup.firmaciv": "Firma: Civilization",
    "creativetab.firmaciv_tab": "Firma: Civilization",
    "creativetab.watercraft_tab": "Watercraft",
    "creativetab.navigation_tab": "Navigation",

    "tfc.recipe.barrel.firmaciv.barrel.large_waterproof_hide_olive": "Large Waterproof Hide",
    "tfc.recipe.barrel.firmaciv.barrel.large_waterproof_hide_tallow": "Large Waterproof Hide",

    "copy_latitude": "Copy Latitude to Clipboard",
    "copy_longitude": "Copy Longitude to Clipboard",
    "copy_latlon": "Copy Latitude and Longitude to Clipboard",
    "copy_altitude": "Copy Altitude to Clipboard",

    "firmaciv.advancements.kayak_paddle.title": "Double Trouble",
    "firmaciv.advancements.kayak_paddle.description": "Craft a Kayak Paddle",
    "firmaciv.advancements.canoe.title": "Burnout Paradise",
    "firmaciv.advancements.canoe.description": "Attempt to light a canoe hull",
    "firmaciv.advancements.oar.title": "Oaring my Paddleboat",
    "firmaciv.advancements.oar.description": "Craft an Oar",
    "firmaciv.advancements.kayak.title": "I'll carry you home tonight",
    "firmaciv.advancements.kayak.description": "Craft a Kayak",
    "firmaciv.advancements.nav_clock.title": "Get your time from the Admiral",
    "firmaciv.advancements.nav_clock.description": "Craft a Navigator's Timepiece",
    "firmaciv.advancements.sextant.title": "The Stars Will Aid",
    "firmaciv.advancements.sextant.description": "Craft a Sextant",
    "firmaciv.advancements.barometer.title": "Surf and/or Turf",
    "firmaciv.advancements.barometer.description": "Craft a Barometer",
    "firmaciv.advancements.oarlock.title": "The Montlake Cut",
    "firmaciv.advancements.oarlock.description": "Smith an Oarlock"

}
